# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpsblog', '0002_naverpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawlnaver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('original_url', models.URLField()),
                ('thumbnail_image_element', models.URLField()),
            ],
        ),
    ]
