# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpsblog', '0003_crawlnaver'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverpost',
            name='keyword',
            field=models.CharField(default='내용 없음', max_length=16),
            preserve_default=False,
        ),
    ]
