# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpsblog', '0004_naverpost_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naverpost',
            name='keyword',
        ),
        migrations.AddField(
            model_name='crawlnaver',
            name='keyword',
            field=models.CharField(default='no query', max_length=16),
            preserve_default=False,
        ),
    ]
