# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpsblog', '0007_auto_20170322_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
